version = 0.1

[default.deploy.parameters]
stack_name = "cloud-image-service-dev"
resolve_s3 = true
s3_prefix = "cloud-image-service-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"img-source-bucket-demo\" ProcessedBucketName=\"img-processed-bucket-demo\" CloudFrontDomain=\"\" RedisHost=\"\" EnableRedis=\"false\" EnableCloudFront=\"false\""
image_repositories = []
